import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class DatabaseService {
  static final SupabaseClient _supabase = Supabase.instance.client;

  // Safely convert to double for your float8 columns
  static double? _parseDouble(dynamic value) {
    if (value == null) return null;
    if (value is num) return value.toDouble();
    if (value is String) return double.tryParse(value);
    return null;
  }

  static Future<void> uploadEdgeData(Map<String, dynamic> payloadMap) async {
    try {
      debugPrint('Supabase: Preparing to upload payload: $payloadMap');

      final dataToInsert = <String, dynamic>{
        'latitude': _parseDouble(payloadMap['latitude']),
        'longitude': _parseDouble(payloadMap['longitude']),
      };

      // Map to float8 columns
      if (payloadMap.containsKey('temperature_c')) {
        dataToInsert['temperature'] = _parseDouble(payloadMap['temperature_c']);
      }
      if (payloadMap.containsKey('humidity_percent')) {
        dataToInsert['humidity'] = _parseDouble(payloadMap['humidity_percent']);
      }

      // Map to bool column
      if (payloadMap.containsKey('trash_detected')) {
        dataToInsert['trash_detected'] = payloadMap['trash_detected'];
      }

      // CRITICAL FIX: Pass exactly as a String for your 'text' column
      if (payloadMap.containsKey('toxicity_level')) {
        dataToInsert['toxicity_level'] = payloadMap['toxicity_level']
            ?.toString();
      }

      // Map to timestamptz column
      dataToInsert['device_timestamp'] = DateTime.now()
          .toUtc()
          .toIso8601String();

      debugPrint('Supabase: PUSHING THIS TO CLOUD: $dataToInsert');

      // id (int8) is auto-generated by Supabase, so we do not include it here.
      await _supabase.from('city_scans').insert(dataToInsert);

      debugPrint('Supabase: Upload successful!');
    } catch (e) {
      debugPrint('Supabase upload failed: $e');
    }
  }
}
