import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class DatabaseService {
  static final SupabaseClient _supabase = Supabase.instance.client;

  static Future<void> uploadEdgeData(Map<String, dynamic> payloadMap) async {
    try {
      // Map to exact required schema
      final dataToInsert = {
        'latitude': (payloadMap['latitude'] as num?)?.toDouble(),
        'longitude': (payloadMap['longitude'] as num?)?.toDouble(),
        'tag': payloadMap['detectedTag']?.toString() ?? payloadMap['tag']?.toString() ?? 'Unknown',
        'confidence': payloadMap['confidence']?.toString() ?? '0.0',
        // 'created_at' is usually auto-generated by Supabase, so we omit timestamp here
      };
      
      await _supabase.from('city_scans').insert(dataToInsert);
      
    } catch (e) {
      debugPrint('Supabase upload failed: $e');
      // Robust error handling: fail silently without crashing the app, 
      // as per requirements (drop payloads if there is no internet connection).
    }
  }
}
